FROM php:7.3-fpm-stretch

RUN apt-get update && apt-get install -y libpng-dev libfreetype6-dev libjpeg62-turbo-dev libxml2-dev unzip
RUN docker-php-ext-install mysqli pdo pdo_mysql xml
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install gd

ADD https://github.com/fisharebest/webtrees/releases/download/2.0.0/webtrees-2.0.0.zip /var/www/
RUN cd /var/www \
  && unzip /var/www/webtrees-2.0.0.zip \
  && mv webtrees/* . \
  && rmdir webtrees \
  && rm webtrees-2.0.0.zip \
  && printf "post_max_side = 40M\nupload_max_filesize = 40M\n" > /usr/local/etc/php/conf.d/php-upload.ini
